### ISSUE TITLE
Cannot get comments to reliably save to the data folder

### ISSUE THREAD

**Issue by mikegcox** [getgrav/grav-plugin-comments#66]
I am having trouble getting the comments module to work reliably.  Site is hosted on Wirenine (Apache, PHP 7.0) .  I have `cache_enable: false` configured in the page header.  I adjusted the process order to post before sending mail and I have tried it default too.  It works sporadically.  It does send mail, but not every time either. Last time I tried to get it working, it would work after I did a clear-cache for the the site, but only once.  This time I cannot get it to post at all.

Here is my config file:

```
enabled: true

enable_on_routes:
  - '/wallpapers'

disable_on_routes:
  - /blog/blog-post-to-ignore
  - /ignore-this-route
  #- '/blog/daring-fireball-link'

form:
    name: comments
    fields:
        - name: name
          label: Name
          placeholder: PLUGIN_COMMENTS.NAME_PLACEHOLDER
          classes: form-control
          autocomplete: on
          type: text
          validate:
            required: true

        - name: email
          label: Email
          placeholder: PLUGIN_COMMENTS.EMAIL_PLACEHOLDER
          classes: form-control
          type: email
          validate:
            required: true

        - name: text
          label: Comment
          placeholder: PLUGIN_COMMENTS.MESSAGE_PLACEHOLDER
          type: textarea
          classes: form-control
          validate:
            required: true

        - name: date
          type: hidden
          process:
            fillWithCurrentDateTime: true

        - name: title
          type: hidden
          evaluateDefault: grav.page.header.title

        - name: lang
          type: hidden
          evaluateDefault: grav.language.getLanguage

        - name: path
          type: hidden
          evaluateDefault: grav.uri.path


    buttons:
        - type: submit
          value: PLUGIN_COMMENTS.SUBMIT_COMMENT_BUTTON_TEXT
          classes: 'btn btn-md btn-black'

    process:
        - addComment:
        - message: PLUGIN_COMMENTS.THANK_YOU_MESSAGE    
        - email:
            subject: PLUGIN_COMMENTS.EMAIL_NEW_COMMENT_SUBJECT
            body: "{% include 'forms/data.html.twig' %}"
        - reset: true
```
